<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <ManagedDir>$(GameDir)\GraveyardKeeper2_Data\Managed</ManagedDir>
    <BepInExDir>$(GameDir)\BepInEx\core</BepInExDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(GameDir)\GraveyardKeeper2_Data\Managed\Sirenix.Serialization.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="BepInEx">
      <HintPath>$(BepInExDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>$(BepInExDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="LazyBearTechnology">
      <HintPath>$(ManagedDir)\LazyBearTechnology.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>$(ManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
